name = "y-partyserver-tictactoe"
main = "server/index.ts"
compatibility_date = "2024-01-01"

[durable_objects]
bindings = [
  { name = "TICTACTOE_ROOM", class_name = "TicTacToeRoom" }
]

[[migrations]]
tag = "v1"
new_classes = ["TicTacToeRoom"]

[env.production]
name = "y-partyserver-tictactoe-production"
