name = "valtio-y-stickynotes"
main = "server/index.ts"
compatibility_date = "2024-12-01"

[durable_objects]
bindings = [
  { name = "STICKYNOTES_DO", class_name = "StickyNotesRoom" }
]

[[migrations]]
tag = "v1"
new_classes = ["StickyNotesRoom"]
